apiVersion: v1
kind: Pod
metadata:
  name: podtest1
spec:
  containers:
    - name: containertest1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
    - name: containertest2
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
    - name: containertest3
      image: nginx:alpine
