apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  containers:
  - name: pod-secret
    image: nginx:alpine
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: secret1
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret1
            key: password