apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - image: nginx:alpine
    name: container-test
    volumeMounts:
    - mountPath: /var/log/nginx
      name: vol
  volumes:
  - name: vol
    emptyDir: {}