apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test2
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: deployment-test2
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-test2
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
