apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: martinbobbio/backend-hands-on:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30040
    targetPort: 9090
