apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rstest
  labels:
    app: rstest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: podlabel
  template:
    metadata:
      labels:
        app: podlabel
    spec:
      containers:
      - name: container1
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo container1 > index.html && python -m http.server 8082']
      - name: container2
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo container2 > index.html && python -m http.server 8083']